theme: minima
title: Welcome to my Website!
author: Enoch
email: emkang@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is just a general website about my basic information for my Comp. Sci. FInal project!
  I hope you learned a little about me and enjoy it!

# social links
twitter_username: ekstremers
github_username:  Ekstremers

show_excerpts: true # set to false to remove excerpts on the homepage
